
FROM mysql:5.7

EXPOSE 3306
# # Environment variables
ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes

# RUN mysql -u root -p
# # Allows you to change the value of "max_allowed_packet"
# # ADD ["mysqlconf/gatewaymy.cnf", "/etc/mysql/conf.d/conf_mysql.cnf"]

# # Create Database
# RUN	mkdir /usr/sql
# RUN	chmod 644 /usr/sql


# RUN /etc/init.d/mysql start && \
#       mysql -u root -p password -e "CREATE DATABASE dropApp"

# ADD reviews.sql /docker-entrypoint-initdb.d
